###

GET http://localhost:5000/post

###

GET http://localhost:5000/post?sender=69469337bda8e6485e5c88e8

###

GET http://localhost:5000/post/694d36e5841dc6be59183449

###
POST http://localhost:5000/post
Content-Type: application/json  

{
    "title": "my best trip",
    "mapLink": "https://www.google.com/maps",
    "price": 4000,
    "numberOfDays": 14,
    "location": {
      "country":"USA"
    },
    "description": "my trip to america",
    "photos": ["myphoto1.jpg"]
}

###
PUT http://localhost:5000/post/694d36e5841dc6be59183449
Content-Type: application/json  

{
  "title": "my updated trip"
}

###
GET http://localhost:5000/comment

###
GET http://localhost:5000/comment?post=694d36e5841dc6be59183449

###
GET http://localhost:5000/comment/694d38ec4e31b4d37ec128dc

###
POST http://localhost:5000/comment
Content-Type: application/json  

{
    "user": "69469337bda8e6485e5c88e8",
    "post": "694d36e5841dc6be59183449",
    "text": "Great trip!"
}

###
PUT http://localhost:5000/comment/694d38ec4e31b4d37ec128dc
Content-Type: application/json  

{
  "text": "Updated comment text"
}

###
DELETE http://localhost:5000/comment/694d38ec4e31b4d37ec128dc