###

GET http://localhost:5000/post

###

GET http://localhost:5000/post?sender=69469337bda8e6485e5c88e8

###

GET http://localhost:5000/post/694c4ed74479bc6ffd69f722

###
POST http://localhost:5000/post
Content-Type: application/json  

{
    "sender": "69469337bda8e6485e5c88e8",
    "title": "my trip",
    "mapLink": "https://www.google.com/maps",
    "price": 400,
    "numberOfDays": 14,
    "location": {
      "country":"IL"
    },
    "description": "my trip to israel",
    "photos": ["myphoto1.jpg"]
}

###
PUT http://localhost:5000/post/694c4ed74479bc6ffd69f722
Content-Type: application/json  

{
  "title": "my updated trip"
}

###
GET http://localhost:5000/comment

###
GET http://localhost:5000/comment?post=694c4ed74479bc6ffd69f722

###
GET http://localhost:5000/comment/694c513469e6230f60320c07

###
POST http://localhost:5000/comment
Content-Type: application/json  

{
    "user": "69469337bda8e6485e5c88e8",
    "post": "694c4ed74479bc6ffd69f722",
    "text": "Great trip!"
}

###
PUT http://localhost:5000/comment/694c513469e6230f60320c07
Content-Type: application/json  

{
  "text": "Updated comment text"
}

###
DELETE http://localhost:5000/comment/694c513469e6230f60320c07